# Rust Formatting Configuration
# Equivalent to Biome formatter settings
# Requires: rustup component add rustfmt

edition = "2021"

# Indentation (tabs, 2-width equivalent visual)
hard_tabs = true
tab_spaces = 2

# Line width
max_width = 80
use_small_heuristics = "Default"

# Line endings (LF)
newline_style = "Unix"

# Imports
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Formatting style
brace_style = "SameLineWhere"
fn_single_line = false
where_single_line = false
trailing_comma = "Vertical"
trailing_semicolon = true
use_field_init_shorthand = true
use_try_shorthand = true

# Comments
comment_width = 80
wrap_comments = true
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true

# Match arms
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true

# Misc
condense_wildcard_suffixes = true
edition = "2021"
emit_mode = "Files"
error_on_line_overflow = false
error_on_unformatted = false
force_explicit_abi = true
force_multiline_blocks = false
format_generated_files = false
format_macro_matchers = true
format_macro_bodies = true
format_strings = false
hex_literal_case = "Upper"
merge_derives = true
overflow_delimited_expr = false
remove_nested_parens = true
reorder_impl_items = true
short_array_element_width_threshold = 10
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 0
struct_lit_single_line = true
unstable_features = false
version = "Two"
